# Workflow name
name: "Chromatic Deployment"

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run:
          yarn install --immutable --immutable-cache --check-cache
          #👇 Adds Chromatic as a step in the workflow
      - uses:
          chromaui/action@latest
          
          # Options required for Chromatic's GitHub Action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
